/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/6.6.1/userguide/multi_project_builds.html
 */

rootProject.name = "account-manager"
include("account.manager.core.entity")
include("account.managemer.core.entity")
include("account.manager.core.usecase")
include("adapter:controller:spring-controller")
findProject(":adapter:controller:spring-controller")?.name = "account.manager.adapter.spring.controller"
include("adapter:controller:vertx-controller")
findProject(":adapter:controller:vertx-controller")?.name = "account.manager.adapter.vertx.controller"
include("adapter:repository:in-memory")
findProject(":adapter:repository:in-memory")?.name = "account.manager.adapter.repository.inmemory"
include("adapter:repository:h2")
findProject(":adapter:repository:h2")?.name = "account.manager.adapter.repository.h2"
